import { AchievementDefinition } from './types';

export const ACHIEVEMENT_CATALOG: AchievementDefinition[] = [
  {
    type: 'FIRST_TRIP',
    title: 'First Trip',
    description: 'Create your very first travel itinerary in GhumneChalo.',
    category: 'TRIPS',
    rarity: 'COMMON',
    icon: 'Compass',
    targetValue: 1,
    unit: 'trip',
  },
  {
    type: 'TRAVEL_EXPLORER',
    title: 'Travel Explorer',
    description: 'Discover and save 3 or more dream destinations or places of interest.',
    category: 'EXPLORATION',
    rarity: 'COMMON',
    icon: 'MapPin',
    targetValue: 3,
    unit: 'places',
  },
  {
    type: 'FOODIE_EXPLORER',
    title: 'Foodie Explorer',
    description: 'Add culinary stops, cafes, or local food experiences to your plans.',
    category: 'CULINARY',
    rarity: 'UNCOMMON',
    icon: 'Utensils',
    targetValue: 2,
    unit: 'food spots',
  },
  {
    type: 'NATURE_LOVER',
    title: 'Nature Lover',
    description: 'Plan visits to scenic outdoors, parks, beaches, lakes, or mountains.',
    category: 'NATURE',
    rarity: 'UNCOMMON',
    icon: 'TreePine',
    targetValue: 2,
    unit: 'nature spots',
  },
  {
    type: 'MULTI_TRIP_PLANNER',
    title: 'Multi-Trip Planner',
    description: 'Plan 3 or more distinct journeys across India and beyond.',
    category: 'TRIPS',
    rarity: 'RARE',
    icon: 'Briefcase',
    targetValue: 3,
    unit: 'trips',
  },
  {
    type: 'BUDGET_MASTER',
    title: 'Budget Master',
    description: 'Set a trip budget and track 2 or more expenses to keep spending in check.',
    category: 'FINANCE',
    rarity: 'RARE',
    icon: 'Wallet',
    targetValue: 2,
    unit: 'expenses tracked',
  },
  {
    type: 'ITINERARY_ARCHITECT',
    title: 'Itinerary Architect',
    description: 'Schedule 5 or more planned activities into your trip itineraries.',
    category: 'PLANNING',
    rarity: 'UNCOMMON',
    icon: 'CalendarCheck',
    targetValue: 5,
    unit: 'activities',
  },
  {
    type: 'PACKING_PRO',
    title: 'Packing Pro',
    description: 'Check off 5 items in your smart packing checklist before you go.',
    category: 'PREPARATION',
    rarity: 'COMMON',
    icon: 'Luggage',
    targetValue: 5,
    unit: 'packed items',
  },
  {
    type: 'WAYFARER',
    title: 'Wayfarer',
    description: 'Add 2 or more transit bookings (flights, trains, buses, cabs) to your trips.',
    category: 'TRANSIT',
    rarity: 'RARE',
    icon: 'Plane',
    targetValue: 2,
    unit: 'transits',
  },
];

export const RARITY_POINTS: Record<string, number> = {
  COMMON: 10,
  UNCOMMON: 25,
  RARE: 50,
  LEGENDARY: 100,
};
